# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            teztools.client:
                base_uri: 'https://api.teztools.io/v1/'
                headers:
                    Accept: 'application/json'

    cache:
        app: cache.adapter.redis
        default_redis_provider: app.redis_provider

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
