security:
    enable_authenticator_manager: true
    providers:
        members:
            id: PezosSandbox\Infrastructure\Symfony\Security\MemberUserProvider

    firewalls:
        main:
            custom_authenticator:
                - PezosSandbox\Infrastructure\Symfony\Security\TezosAuthenticator
            entry_point: form_login
            pattern: ^/
            lazy: true
            form_login:
                login_path: /
            logout:
                path: app_logout

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/member-area, roles: ROLE_MEMBER }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
