security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: auto

    providers:
        members:
            id: PezosSandbox\Infrastructure\Symfony\Security\MemberUserProvider
        admins:
            memory:
                users:
                    admin:
                        {
                            password: '%env(ADMIN_PASSWORD)%',
                            roles: ['ROLE_ADMIN'],
                        }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        member_area:
            pattern: ^/
            anonymous: lazy
            provider: members
            guard:
                authenticator:
                    - PezosSandbox\Infrastructure\Symfony\Security\AccessTokenAuthenticator
            logout:
                path: logout

        admin_area:
            pattern: ^/admin-area
            http_basic:
                provider: admins
                realm: Admin area
            logout:
                path: admin_area_logout

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin-area, roles: ROLE_ADMIN }
        - { path: ^/member-area, roles: ROLE_MEMBER }
