security:
    providers:
        members:
            id: PezosSandbox\Infrastructure\Symfony\Security\MemberUserProvider

    firewalls:
        main:
            pattern: ^/
            anonymous: lazy
            form_login:
                login_path: /
            logout:
                path: app_logout
            provider: members
            guard:
                authenticator:
                    - PezosSandbox\Infrastructure\Symfony\Security\LoginFormAuthenticator

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/member-area, roles: ROLE_MEMBER }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
