security:
    encoders:
        PezosSandbox\Application\Members\Member:
            algorithm: auto

    providers:
        members:
            id: PezosSandbox\Infrastructure\Symfony\Security\MemberUserProvider

    firewalls:
        main:
            pattern: ^/
            anonymous: lazy
            form_login: ~
            logout:
                path: app_logout
            provider: members
            guard:
                authenticator:
                    - PezosSandbox\Infrastructure\Symfony\Security\LoginFormAuthenticator

    access_control:
        - { path: ^/$, roles: ROLE_MEMBER }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
