version: '3.4'

services:
    nginx:
        build:
            dockerfile: docker/php/Dockerfile
            context: .
            target: symfony_nginx
        depends_on:
            - php

    php:
        build:
            dockerfile: docker/php/Dockerfile
            context: .
            target: symfony_php
            args:
                SYMFONY_VERSION: ${SYMFONY_VERSION:-}
                STABILITY: ${STABILITY:-stable}
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s
        environment:
            - SYMFONY_VERSION
        volumes:
            - var:/srv/app/var/

volumes:
    var:
