version: '3.4'

services:
    nginx:
        image: bzzhh/pezos-sandbox-development-nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./public:/srv/app/public

    php:
        image: bzzhh/pezos-sandbox-development-php:latest
        volumes:
            # The "cached" option has no effect on Linux but improves performance on Mac
            - ./:/srv/app:rw,cached
            - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
            # If you develop on Mac you can remove the var/ directory from the bind-mount
            # for better performance by enabling the next line
            # - /srv/app/var
        env_file:
            - .env

    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data

volumes:
    var:
    redis_data:
