version: '3.5'

services:
    # test prod container (use .env.docker)
    # pezos:
    #     image: bzzhh/pezos:latest
    #     ports:
    #         - 7800:8080

    db:
        image: postgres:13-alpine
        environment:
            POSTGRES_PASSWORD: secret
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        command: ['postgres', '-c', 'log_statement=all']

    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data

    adminer:
        image: adminer
        ports:
            - 7000:8080
volumes:
    var:
    db_data:
    redis_data:
