version: '3.4'

services:
    nginx:
        build:
            dockerfile: docker/php/Dockerfile
            context: .
            target: symfony_nginx
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            target: symfony_php
            args:
                SYMFONY_VERSION: ${SYMFONY_VERSION:-}
                STABILITY: ${STABILITY:-stable}
        healthcheck:
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 30s
        environment:
            - SYMFONY_VERSION
        volumes:
            - var:/srv/app/var/

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 'secret'
            POSTGRES_USER: 'pezos_sandbox'
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - 5432:5432

    adminer:
        image: adminer
        ports:
            - 7000:8080

volumes:
    var:
    db_data:
