# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    router.request_context.scheme: '%env(SITE_BASE_SCHEME)%'
    router.request_context.host: '%env(SITE_BASE_HOST)%'
    site_base_scheme: '%env(SITE_BASE_SCHEME)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $siteBaseScheme: '%site_base_scheme%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    #    App\:
    #        resource: '../src/*'
    #        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Infrastructure\Symfony\Controller\:
        resource: '../src/Infrastructure/Symfony/Controller'
        tags: ['controller.service_arguments']

    Infrastructure\Symfony\Command\:
        resource: '../src/Infrastructure/Symfony/Command'

    Infrastructure\Symfony\Form\:
        resource: '../src/Infrastructure/Symfony/Form'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Application\ApplicationInterface:
        factory: ['@Infrastructure\ServiceContainer', 'application']
        public: true

    Application\EventDispatcher:
        factory: ['@Infrastructure\ServiceContainer', 'eventDispatcher']

    Infrastructure\ProductionServiceContainer: ~

    Infrastructure\Symfony\SetSchemeOnRequestContext: ~

    Infrastructure\Symfony\AddFlashMessageToSession:
        public: true
    
    Infrastructure\Symfony\LogEvents:
        public: true
