name: main
on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build and Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Build
              run: |
                  echo "SYMFONY_DECRYPTION_SECRET=${{ secrets.SYMFONY_DECRYPTION_SECRET}}" >> .env.prod
                  mv .env.prod .env
                  docker build -t bzzhh/pezos:latest .
            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push to Docker Hub
              run: docker push bzzhh/pezos:latest
            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: ${{ secrets.KNOWN_HOSTS }}
            - name: Deploy
              run: |
                  ssh deploy@${{ secrets.PROD_SERVER_IP }} "docker rmi -f bzzhh/pezos:latest"
                  ssh deploy@${{ secrets.PROD_SERVER_IP }} "echo ${{ secrets.DOCKER_PASSWORD}} | docker login --username bzzhh --password-stdin && docker pull bzzhh/pezos:latest"
                  ssh deploy@${{ secrets.PROD_SERVER_IP }} "docker rm -f pezos"
                  ssh deploy@${{ secrets.PROD_SERVER_IP }} "docker run --name pezos -p 7800:8080 -d bzzhh/pezos:latest"
                  sleep 3
                  ssh deploy@${{ secrets.PROD_SERVER_IP }} "docker exec -u nobody pezos sh -c 'export APP_RUNTIME_ENV=prod; php bin/console secrets:decrypt-to-local --force'"
                  ssh deploy@${{ secrets.PROD_SERVER_IP }} "docker exec -u nobody pezos bin/console doctrine:database:create --if-not-exists"
                  ssh deploy@${{ secrets.PROD_SERVER_IP }} "docker exec -u nobody pezos bin/console doctrine:migrations:migrate --no-interaction"
