name: main
on:
    push:
        branches:
            - pezos.fi

jobs:
    build:
        name: Build and Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Build
              run: |
                  docker build -t bzzhh/pezos:latest .
            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push to Docker Hub
              run: docker push bzzhh/pezos:latest
            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: ${{ secrets.KNOWN_HOSTS }}
            - name: Deploy
              run: ssh deploy@${{ secrets.PROD_SERVER_IP }} "docker rm -f pezos && docker rmi -f $(docker images 'bzzhh/pezos' -a -q) && docker run --name pezos -p 7800:8080 -d bzzhh/pezos:latest"
